name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m venv .venv
        .\.venv\Scripts\pip install -r requirements.txt
        .\.venv\Scripts\pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        .\.venv\Scripts\pyinstaller app.spec --noconfirm

    - name: Create zip archive
      run: |
        mkdir build_output
        xcopy dist\DownloadGod build_output\DownloadGod.exe /Y
        xcopy /E dist\DownloadGod\_internal build_output\_internal
        powershell Compress-Archive -Path build_output\* -DestinationPath build_output.zip

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: downloadgod-build
        path: build_output.zip
        retention-days: 5
